'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReferencePublished
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AntwortRestkontingent", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AntwortRestkontingent
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private KontingentField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FehlerField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Kontingent() As Integer
            Get
                Return Me.KontingentField
            End Get
            Set
                If (Me.KontingentField.Equals(value) <> true) Then
                    Me.KontingentField = value
                    Me.RaisePropertyChanged("Kontingent")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Fehler() As String
            Get
                Return Me.FehlerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FehlerField, value) <> true) Then
                    Me.FehlerField = value
                    Me.RaisePropertyChanged("Fehler")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AntwortOffeneKontrolldateien", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AntwortOffeneKontrolldateien
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AusweiseField() As ServiceReferencePublished.Ausweis
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FehlerField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Ausweise() As ServiceReferencePublished.Ausweis()
            Get
                Return Me.AusweiseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AusweiseField, value) <> true) Then
                    Me.AusweiseField = value
                    Me.RaisePropertyChanged("Ausweise")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Fehler() As String
            Get
                Return Me.FehlerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FehlerField, value) <> true) Then
                    Me.FehlerField = value
                    Me.RaisePropertyChanged("Fehler")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ausweis", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Ausweis
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegistriernummerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AusstellerField As String
        
        Private NummerErzeugtAmField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Registriernummer() As String
            Get
                Return Me.RegistriernummerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegistriernummerField, value) <> true) Then
                    Me.RegistriernummerField = value
                    Me.RaisePropertyChanged("Registriernummer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Aussteller() As String
            Get
                Return Me.AusstellerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AusstellerField, value) <> true) Then
                    Me.AusstellerField = value
                    Me.RaisePropertyChanged("Aussteller")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property NummerErzeugtAm() As Date
            Get
                Return Me.NummerErzeugtAmField
            End Get
            Set
                If (Me.NummerErzeugtAmField.Equals(value) <> true) Then
                    Me.NummerErzeugtAmField = value
                    Me.RaisePropertyChanged("NummerErzeugtAm")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Evaluation_Result_List", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Evaluation_Result_List
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Evaluation_ListField() As ServiceReferencePublished.Evaluation_Result
        
        Private Errors_detectedField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Evaluation_List() As ServiceReferencePublished.Evaluation_Result()
            Get
                Return Me.Evaluation_ListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Evaluation_ListField, value) <> true) Then
                    Me.Evaluation_ListField = value
                    Me.RaisePropertyChanged("Evaluation_List")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property Errors_detected() As Boolean
            Get
                Return Me.Errors_detectedField
            End Get
            Set
                If (Me.Errors_detectedField.Equals(value) <> true) Then
                    Me.Errors_detectedField = value
                    Me.RaisePropertyChanged("Errors_detected")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Evaluation_Result", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Evaluation_Result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private KeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CheckOnField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Error_WarningField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TagPathField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Key() As String
            Get
                Return Me.KeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.KeyField, value) <> true) Then
                    Me.KeyField = value
                    Me.RaisePropertyChanged("Key")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property CheckOn() As String
            Get
                Return Me.CheckOnField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CheckOnField, value) <> true) Then
                    Me.CheckOnField = value
                    Me.RaisePropertyChanged("CheckOn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Result() As String
            Get
                Return Me.ResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultField, value) <> true) Then
                    Me.ResultField = value
                    Me.RaisePropertyChanged("Result")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Error_Warning() As String
            Get
                Return Me.Error_WarningField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Error_WarningField, value) <> true) Then
                    Me.Error_WarningField = value
                    Me.RaisePropertyChanged("Error_Warning")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property TagPath() As String
            Get
                Return Me.TagPathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TagPathField, value) <> true) Then
                    Me.TagPathField = value
                    Me.RaisePropertyChanged("TagPath")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", ConfigurationName:="ServiceReferencePublished.DibtEnergieAusweisServiceSoap")>  _
    Public Interface DibtEnergieAusweisServiceSoap
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname doc aus Namespace http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Datenre"& _ 
            "gistratur", ReplyAction:="*")>  _
        Function Datenregistratur(ByVal request As ServiceReferencePublished.DatenregistraturRequest) As ServiceReferencePublished.DatenregistraturResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Datenre"& _ 
            "gistratur", ReplyAction:="*")>  _
        Function DatenregistraturAsync(ByVal request As ServiceReferencePublished.DatenregistraturRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.DatenregistraturResponse)
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname doc aus Namespace http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Zusatzd"& _ 
            "atenErfassung", ReplyAction:="*")>  _
        Function ZusatzdatenErfassung(ByVal request As ServiceReferencePublished.ZusatzdatenErfassungRequest) As ServiceReferencePublished.ZusatzdatenErfassungResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Zusatzd"& _ 
            "atenErfassung", ReplyAction:="*")>  _
        Function ZusatzdatenErfassungAsync(ByVal request As ServiceReferencePublished.ZusatzdatenErfassungRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.ZusatzdatenErfassungResponse)
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname Username aus Namespace http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Restkon"& _ 
            "tingent", ReplyAction:="*")>  _
        Function Restkontingent(ByVal request As ServiceReferencePublished.RestkontingentRequest) As ServiceReferencePublished.RestkontingentResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Restkon"& _ 
            "tingent", ReplyAction:="*")>  _
        Function RestkontingentAsync(ByVal request As ServiceReferencePublished.RestkontingentRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.RestkontingentResponse)
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname Username aus Namespace http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/OffeneK"& _ 
            "ontrolldateien", ReplyAction:="*")>  _
        Function OffeneKontrolldateien(ByVal request As ServiceReferencePublished.OffeneKontrolldateienRequest) As ServiceReferencePublished.OffeneKontrolldateienResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/OffeneK"& _ 
            "ontrolldateien", ReplyAction:="*")>  _
        Function OffeneKontrolldateienAsync(ByVal request As ServiceReferencePublished.OffeneKontrolldateienRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.OffeneKontrolldateienResponse)
        
        'CODEGEN: Es wird ein Nachrichtenvertrag generiert, da Elementname Username aus Namespace http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService nicht als "nillable" (nullwertfähig) gekennzeichnet ist.
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Kontrol"& _ 
            "ldateiPruefen", ReplyAction:="*")>  _
        Function KontrolldateiPruefen(ByVal request As ServiceReferencePublished.KontrolldateiPruefenRequest) As ServiceReferencePublished.KontrolldateiPruefenResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService/Kontrol"& _ 
            "ldateiPruefen", ReplyAction:="*")>  _
        Function KontrolldateiPruefenAsync(ByVal request As ServiceReferencePublished.KontrolldateiPruefenRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.KontrolldateiPruefenResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DatenregistraturRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Datenregistratur", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.DatenregistraturRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.DatenregistraturRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class DatenregistraturRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public doc As System.Xml.XmlElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal doc As System.Xml.XmlElement)
            MyBase.New
            Me.doc = doc
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DatenregistraturResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DatenregistraturResponse", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.DatenregistraturResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.DatenregistraturResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class DatenregistraturResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DatenregistraturResult As System.Xml.XmlElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DatenregistraturResult As System.Xml.XmlElement)
            MyBase.New
            Me.DatenregistraturResult = DatenregistraturResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZusatzdatenErfassungRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ZusatzdatenErfassung", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.ZusatzdatenErfassungRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.ZusatzdatenErfassungRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class ZusatzdatenErfassungRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public doc As System.Xml.XmlElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public ausweisnummer As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public passwort As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal doc As System.Xml.XmlElement, ByVal ausweisnummer As String, ByVal username As String, ByVal passwort As String)
            MyBase.New
            Me.doc = doc
            Me.ausweisnummer = ausweisnummer
            Me.username = username
            Me.passwort = passwort
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ZusatzdatenErfassungResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ZusatzdatenErfassungResponse", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.ZusatzdatenErfassungResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.ZusatzdatenErfassungResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class ZusatzdatenErfassungResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ZusatzdatenErfassungResult As System.Xml.XmlElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ZusatzdatenErfassungResult As System.Xml.XmlElement)
            MyBase.New
            Me.ZusatzdatenErfassungResult = ZusatzdatenErfassungResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RestkontingentRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Restkontingent", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.RestkontingentRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.RestkontingentRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class RestkontingentRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Passwort As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Username As String, ByVal Passwort As String)
            MyBase.New
            Me.Username = Username
            Me.Passwort = Passwort
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RestkontingentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RestkontingentResponse", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.RestkontingentResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.RestkontingentResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class RestkontingentResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RestkontingentResult As ServiceReferencePublished.AntwortRestkontingent
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RestkontingentResult As ServiceReferencePublished.AntwortRestkontingent)
            MyBase.New
            Me.RestkontingentResult = RestkontingentResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class OffeneKontrolldateienRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="OffeneKontrolldateien", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.OffeneKontrolldateienRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.OffeneKontrolldateienRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class OffeneKontrolldateienRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Passwort As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public NurPersonenbezogeneAusweiseErmitteln As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Username As String, ByVal Passwort As String, ByVal NurPersonenbezogeneAusweiseErmitteln As Boolean)
            MyBase.New
            Me.Username = Username
            Me.Passwort = Passwort
            Me.NurPersonenbezogeneAusweiseErmitteln = NurPersonenbezogeneAusweiseErmitteln
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class OffeneKontrolldateienResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="OffeneKontrolldateienResponse", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.OffeneKontrolldateienResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.OffeneKontrolldateienResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class OffeneKontrolldateienResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public OffeneKontrolldateienResult As ServiceReferencePublished.AntwortOffeneKontrolldateien
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal OffeneKontrolldateienResult As ServiceReferencePublished.AntwortOffeneKontrolldateien)
            MyBase.New
            Me.OffeneKontrolldateienResult = OffeneKontrolldateienResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class KontrolldateiPruefenRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="KontrolldateiPruefen", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.KontrolldateiPruefenRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.KontrolldateiPruefenRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class KontrolldateiPruefenRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Username As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Passwort As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Ausweisnummer As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Kontrolldatei As System.Xml.XmlElement
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Schemapruefung As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Inhaltpruefung As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Username As String, ByVal Passwort As String, ByVal Ausweisnummer As String, ByVal Kontrolldatei As System.Xml.XmlElement, ByVal Schemapruefung As Boolean, ByVal Inhaltpruefung As Boolean)
            MyBase.New
            Me.Username = Username
            Me.Passwort = Passwort
            Me.Ausweisnummer = Ausweisnummer
            Me.Kontrolldatei = Kontrolldatei
            Me.Schemapruefung = Schemapruefung
            Me.Inhaltpruefung = Inhaltpruefung
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class KontrolldateiPruefenResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="KontrolldateiPruefenResponse", [Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService", Order:=0)>  _
        Public Body As ServiceReferencePublished.KontrolldateiPruefenResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReferencePublished.KontrolldateiPruefenResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://energieausweis.dibt.de/WebServiceEnergie/DibtEnergieAusweisService")>  _
    Partial Public Class KontrolldateiPruefenResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public KontrolldateiPruefenResult As ServiceReferencePublished.Evaluation_Result_List
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal KontrolldateiPruefenResult As ServiceReferencePublished.Evaluation_Result_List)
            MyBase.New
            Me.KontrolldateiPruefenResult = KontrolldateiPruefenResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DibtEnergieAusweisServiceSoapChannel
        Inherits ServiceReferencePublished.DibtEnergieAusweisServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DibtEnergieAusweisServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReferencePublished.DibtEnergieAusweisServiceSoap)
        Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_Datenregistratur(ByVal request As ServiceReferencePublished.DatenregistraturRequest) As ServiceReferencePublished.DatenregistraturResponse Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.Datenregistratur
            Return MyBase.Channel.Datenregistratur(request)
        End Function
        
        Public Function Datenregistratur(ByVal doc As System.Xml.XmlElement) As System.Xml.XmlElement
            Dim inValue As ServiceReferencePublished.DatenregistraturRequest = New ServiceReferencePublished.DatenregistraturRequest()
            inValue.Body = New ServiceReferencePublished.DatenregistraturRequestBody()
            inValue.Body.doc = doc
            Dim retVal As ServiceReferencePublished.DatenregistraturResponse = CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).Datenregistratur(inValue)
            Return retVal.Body.DatenregistraturResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_DatenregistraturAsync(ByVal request As ServiceReferencePublished.DatenregistraturRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.DatenregistraturResponse) Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.DatenregistraturAsync
            Return MyBase.Channel.DatenregistraturAsync(request)
        End Function
        
        Public Function DatenregistraturAsync(ByVal doc As System.Xml.XmlElement) As System.Threading.Tasks.Task(Of ServiceReferencePublished.DatenregistraturResponse)
            Dim inValue As ServiceReferencePublished.DatenregistraturRequest = New ServiceReferencePublished.DatenregistraturRequest()
            inValue.Body = New ServiceReferencePublished.DatenregistraturRequestBody()
            inValue.Body.doc = doc
            Return CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).DatenregistraturAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_ZusatzdatenErfassung(ByVal request As ServiceReferencePublished.ZusatzdatenErfassungRequest) As ServiceReferencePublished.ZusatzdatenErfassungResponse Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.ZusatzdatenErfassung
            Return MyBase.Channel.ZusatzdatenErfassung(request)
        End Function
        
        Public Function ZusatzdatenErfassung(ByVal doc As System.Xml.XmlElement, ByVal ausweisnummer As String, ByVal username As String, ByVal passwort As String) As System.Xml.XmlElement
            Dim inValue As ServiceReferencePublished.ZusatzdatenErfassungRequest = New ServiceReferencePublished.ZusatzdatenErfassungRequest()
            inValue.Body = New ServiceReferencePublished.ZusatzdatenErfassungRequestBody()
            inValue.Body.doc = doc
            inValue.Body.ausweisnummer = ausweisnummer
            inValue.Body.username = username
            inValue.Body.passwort = passwort
            Dim retVal As ServiceReferencePublished.ZusatzdatenErfassungResponse = CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).ZusatzdatenErfassung(inValue)
            Return retVal.Body.ZusatzdatenErfassungResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_ZusatzdatenErfassungAsync(ByVal request As ServiceReferencePublished.ZusatzdatenErfassungRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.ZusatzdatenErfassungResponse) Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.ZusatzdatenErfassungAsync
            Return MyBase.Channel.ZusatzdatenErfassungAsync(request)
        End Function
        
        Public Function ZusatzdatenErfassungAsync(ByVal doc As System.Xml.XmlElement, ByVal ausweisnummer As String, ByVal username As String, ByVal passwort As String) As System.Threading.Tasks.Task(Of ServiceReferencePublished.ZusatzdatenErfassungResponse)
            Dim inValue As ServiceReferencePublished.ZusatzdatenErfassungRequest = New ServiceReferencePublished.ZusatzdatenErfassungRequest()
            inValue.Body = New ServiceReferencePublished.ZusatzdatenErfassungRequestBody()
            inValue.Body.doc = doc
            inValue.Body.ausweisnummer = ausweisnummer
            inValue.Body.username = username
            inValue.Body.passwort = passwort
            Return CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).ZusatzdatenErfassungAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_Restkontingent(ByVal request As ServiceReferencePublished.RestkontingentRequest) As ServiceReferencePublished.RestkontingentResponse Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.Restkontingent
            Return MyBase.Channel.Restkontingent(request)
        End Function
        
        Public Function Restkontingent(ByVal Username As String, ByVal Passwort As String) As ServiceReferencePublished.AntwortRestkontingent
            Dim inValue As ServiceReferencePublished.RestkontingentRequest = New ServiceReferencePublished.RestkontingentRequest()
            inValue.Body = New ServiceReferencePublished.RestkontingentRequestBody()
            inValue.Body.Username = Username
            inValue.Body.Passwort = Passwort
            Dim retVal As ServiceReferencePublished.RestkontingentResponse = CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).Restkontingent(inValue)
            Return retVal.Body.RestkontingentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_RestkontingentAsync(ByVal request As ServiceReferencePublished.RestkontingentRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.RestkontingentResponse) Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.RestkontingentAsync
            Return MyBase.Channel.RestkontingentAsync(request)
        End Function
        
        Public Function RestkontingentAsync(ByVal Username As String, ByVal Passwort As String) As System.Threading.Tasks.Task(Of ServiceReferencePublished.RestkontingentResponse)
            Dim inValue As ServiceReferencePublished.RestkontingentRequest = New ServiceReferencePublished.RestkontingentRequest()
            inValue.Body = New ServiceReferencePublished.RestkontingentRequestBody()
            inValue.Body.Username = Username
            inValue.Body.Passwort = Passwort
            Return CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).RestkontingentAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_OffeneKontrolldateien(ByVal request As ServiceReferencePublished.OffeneKontrolldateienRequest) As ServiceReferencePublished.OffeneKontrolldateienResponse Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.OffeneKontrolldateien
            Return MyBase.Channel.OffeneKontrolldateien(request)
        End Function
        
        Public Function OffeneKontrolldateien(ByVal Username As String, ByVal Passwort As String, ByVal NurPersonenbezogeneAusweiseErmitteln As Boolean) As ServiceReferencePublished.AntwortOffeneKontrolldateien
            Dim inValue As ServiceReferencePublished.OffeneKontrolldateienRequest = New ServiceReferencePublished.OffeneKontrolldateienRequest()
            inValue.Body = New ServiceReferencePublished.OffeneKontrolldateienRequestBody()
            inValue.Body.Username = Username
            inValue.Body.Passwort = Passwort
            inValue.Body.NurPersonenbezogeneAusweiseErmitteln = NurPersonenbezogeneAusweiseErmitteln
            Dim retVal As ServiceReferencePublished.OffeneKontrolldateienResponse = CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).OffeneKontrolldateien(inValue)
            Return retVal.Body.OffeneKontrolldateienResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_OffeneKontrolldateienAsync(ByVal request As ServiceReferencePublished.OffeneKontrolldateienRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.OffeneKontrolldateienResponse) Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.OffeneKontrolldateienAsync
            Return MyBase.Channel.OffeneKontrolldateienAsync(request)
        End Function
        
        Public Function OffeneKontrolldateienAsync(ByVal Username As String, ByVal Passwort As String, ByVal NurPersonenbezogeneAusweiseErmitteln As Boolean) As System.Threading.Tasks.Task(Of ServiceReferencePublished.OffeneKontrolldateienResponse)
            Dim inValue As ServiceReferencePublished.OffeneKontrolldateienRequest = New ServiceReferencePublished.OffeneKontrolldateienRequest()
            inValue.Body = New ServiceReferencePublished.OffeneKontrolldateienRequestBody()
            inValue.Body.Username = Username
            inValue.Body.Passwort = Passwort
            inValue.Body.NurPersonenbezogeneAusweiseErmitteln = NurPersonenbezogeneAusweiseErmitteln
            Return CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).OffeneKontrolldateienAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_KontrolldateiPruefen(ByVal request As ServiceReferencePublished.KontrolldateiPruefenRequest) As ServiceReferencePublished.KontrolldateiPruefenResponse Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.KontrolldateiPruefen
            Return MyBase.Channel.KontrolldateiPruefen(request)
        End Function
        
        Public Function KontrolldateiPruefen(ByVal Username As String, ByVal Passwort As String, ByVal Ausweisnummer As String, ByVal Kontrolldatei As System.Xml.XmlElement, ByVal Schemapruefung As Boolean, ByVal Inhaltpruefung As Boolean) As ServiceReferencePublished.Evaluation_Result_List
            Dim inValue As ServiceReferencePublished.KontrolldateiPruefenRequest = New ServiceReferencePublished.KontrolldateiPruefenRequest()
            inValue.Body = New ServiceReferencePublished.KontrolldateiPruefenRequestBody()
            inValue.Body.Username = Username
            inValue.Body.Passwort = Passwort
            inValue.Body.Ausweisnummer = Ausweisnummer
            inValue.Body.Kontrolldatei = Kontrolldatei
            inValue.Body.Schemapruefung = Schemapruefung
            inValue.Body.Inhaltpruefung = Inhaltpruefung
            Dim retVal As ServiceReferencePublished.KontrolldateiPruefenResponse = CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).KontrolldateiPruefen(inValue)
            Return retVal.Body.KontrolldateiPruefenResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReferencePublished_DibtEnergieAusweisServiceSoap_KontrolldateiPruefenAsync(ByVal request As ServiceReferencePublished.KontrolldateiPruefenRequest) As System.Threading.Tasks.Task(Of ServiceReferencePublished.KontrolldateiPruefenResponse) Implements ServiceReferencePublished.DibtEnergieAusweisServiceSoap.KontrolldateiPruefenAsync
            Return MyBase.Channel.KontrolldateiPruefenAsync(request)
        End Function
        
        Public Function KontrolldateiPruefenAsync(ByVal Username As String, ByVal Passwort As String, ByVal Ausweisnummer As String, ByVal Kontrolldatei As System.Xml.XmlElement, ByVal Schemapruefung As Boolean, ByVal Inhaltpruefung As Boolean) As System.Threading.Tasks.Task(Of ServiceReferencePublished.KontrolldateiPruefenResponse)
            Dim inValue As ServiceReferencePublished.KontrolldateiPruefenRequest = New ServiceReferencePublished.KontrolldateiPruefenRequest()
            inValue.Body = New ServiceReferencePublished.KontrolldateiPruefenRequestBody()
            inValue.Body.Username = Username
            inValue.Body.Passwort = Passwort
            inValue.Body.Ausweisnummer = Ausweisnummer
            inValue.Body.Kontrolldatei = Kontrolldatei
            inValue.Body.Schemapruefung = Schemapruefung
            inValue.Body.Inhaltpruefung = Inhaltpruefung
            Return CType(Me,ServiceReferencePublished.DibtEnergieAusweisServiceSoap).KontrolldateiPruefenAsync(inValue)
        End Function
    End Class
End Namespace
